# Generated by Django 6.0.2 on 2026-02-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Pessoa',
        ),
    ]
