# Generated by Django 6.0.2 on 2026-02-21 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_alter_pessoa_endereco_alter_pessoa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2026, 2, 21)),
        ),
    ]
