# Generated by Django 6.0.2 on 2026-02-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_alter_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome'], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='estado',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='localidade',
            field=models.CharField(blank=True, choices=[('Zona Urbana', 'Zona Urbana'), ('Zona Rural', 'Zona Rural')], null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='servico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='pessoa',
            table='Pessoa',
        ),
    ]
