# Generated by Django 6.0.2 on 2026-02-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_alter_pessoa_options_remove_pessoa_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='servico',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
