# Generated by Django 6.0.2 on 2026-02-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_alter_pessoa_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='localidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
