# Generated by Django 6.0.2 on 2026-02-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_alter_pessoa_localidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='localidade',
            field=models.CharField(blank=True, choices=[('GUAIBIM', 'Guaibim'), ('GUEREM', 'Guerém'), ('SERRA_GRANDE', 'Serra Grande'), ('MARICOABO', 'Maricoabo'), ('OROBO', 'Orobó'), ('CAJAIBA', 'Cajaíba'), ('JAGUARIPE', 'Jaguaripe'), ('BONFIM', 'Bonfim'), ('PEDRA_BRANCA', 'Pedra Branca'), ('TABULEIRO_DA_VARZEA', 'Tabuleiro da Várzea'), ('AGUA_MINERAL', 'Água Mineral'), ('RIO_DO_MEIO', 'Rio do Meio'), ('PIAU', 'Piau'), ('SARAPUI', 'Sarapuí'), ('CANTA_GALO', 'Canta Galo'), ('RIACHAO_DA_SERRA', 'Riachão da Serra')], max_length=50, null=True),
        ),
    ]
