# Generated by Django 6.0.2 on 2026-02-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0009_alter_pessoa_localidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='servico',
        ),
    ]
