# Generated by Django 6.0.2 on 2026-02-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0010_remove_pessoa_servico'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='servico',
            field=models.ManyToManyField(blank=True, null=True, related_name='pessoas', to='servicos.servico'),
        ),
    ]
