# Generated by Django 6.0.2 on 2026-02-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0011_pessoa_servico'),
        ('servicos', '0003_servico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='servico',
            field=models.ManyToManyField(related_name='pessoas', to='servicos.servico'),
        ),
    ]
