# Generated by Django 6.0.2 on 2026-02-28 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0012_alter_pessoa_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='localidade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='servico',
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_propriedade', models.CharField(max_length=100)),
                ('localidade', models.CharField(blank=True, choices=[('GUAIBIM', 'Guaibim'), ('GUEREM', 'Guerém'), ('SERRA_GRANDE', 'Serra Grande'), ('MARICOABO', 'Maricoabo'), ('OROBO', 'Orobó'), ('CAJAIBA', 'Cajaíba'), ('JAGUARIPE', 'Jaguaripe'), ('BONFIM', 'Bonfim'), ('PEDRA_BRANCA', 'Pedra Branca'), ('TABULEIRO_DA_VARZEA', 'Tabuleiro da Várzea'), ('AGUA_MINERAL', 'Água Mineral'), ('RIO_DO_MEIO', 'Rio do Meio'), ('PIAU', 'Piau'), ('SARAPUI', 'Sarapuí'), ('CANTA_GALO', 'Canta Galo'), ('RIACHAO_DA_SERRA', 'Riachão da Serra')], max_length=50, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='pessoas.pessoa')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
                'db_table': 'Propriedade',
                'ordering': ['pessoa__nome', 'nome_propriedade'],
            },
        ),
    ]
