# Generated by Django 6.0.2 on 2026-02-23 15:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0010_remove_pessoa_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(choices=[('CEFIR', 'Cefir'), ('Contrato de comodato', 'Contrato de comodato'), ('Declaração de posse', 'Declaração de posse'), ('CCIR', 'CCIR'), ('ITR', 'ITR')], max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_servico', models.DateField(default=datetime.date.today)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='pessoas.pessoa')),
            ],
        ),
    ]
