# Generated by Django 6.0.2 on 2026-02-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='nome_servico',
            field=models.CharField(choices=[('CEFIR', 'Cefir'), ('Contrato de comodato', 'Contrato de comodato'), ('Declaração de posse', 'Declaração de posse'), ('CCIR', 'CCIR'), ('ITR', 'ITR'), ('Compra e venda', 'Compra e venda'), ('Doação de imóvel', 'Doação de imóvel')], max_length=100),
        ),
    ]
