# Generated by Django 6.0.2 on 2026-02-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servico_nome_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído')], default='Pendente', max_length=20),
        ),
    ]
