# Generated by Django 6.0.2 on 2026-02-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_servico_propriedade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='pessoa',
        ),
    ]
