# Generated by Django 6.0.2 on 2026-02-28 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0013_remove_pessoa_localidade_remove_pessoa_servico_and_more'),
        ('servicos', '0005_remove_servico_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='pessoas.pessoa'),
        ),
    ]
