# Generated by Django 5.2.8 on 2025-11-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='numero_paginas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
